version: '2'
services:
  xtarefas-postsgres:
    extends:
      file: postgresql.yml
      service: postgresql
  xtarefas-minio:
    extends:
      file: minio.yml
      service: minio
  xtarefas-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch